version: '3.8'

services:
  db:
    image: postgres:13
    container_name: todo_db
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo_network

  web:
    build: .
    container_name: todo_web
    environment:
      DATABASE_URL: postgresql://todo_user:todo_password@db:5432/todo_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - todo_network

volumes:
  postgres_data:

networks:
  todo_network:
